<a href="https://colab.research.google.com/github/Young4424/Machine-Learning-Deep-learning-Myself/blob/main/01_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%9D%B4%ED%95%B4%EC%99%80_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# NumPy


## 배열의 생성

### 리스트로 배열 만들기

In [ ]:
a = [1,2,3]
b = [4,5,6]

In [ ]:
a + b # 리스트 연산

[1, 2, 3, 4, 5, 6]

In [ ]:
array_a = np.array(a) # 배열로 변환
array_b = np.array(b)

In [ ]:
array_a + array_b # 배열 연산

array([5, 7, 9])

In [ ]:
a2 = [[1,2,3],
      [4,5,6],
      [7,8,9]]  # 2차원 배열

array_a2 = np.array(a2)


In [ ]:
array_a2 + array_a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a3 = [[[1,2,3],
      [4,5,6],
      [7,8,9]],

      [[1,2,3],
      [4,5,6],
      [7,8,9]],

      [[1,2,3],
      [4,5,6],
      [7,8,9]]]    # 3차원 배열 (2차원 배열 3장)


# ex) RGB 컬러 이미지, 3개의 채널

array_a3 = np.array(a3)

In [ ]:
array_a3 + array_a3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

### 배열 생성 및 초기화

In [ ]:
np.zeros(10) # 0이 10개 들어간 배열 생성, 1차원

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3)) # (행 3, 열 3), 1로 채워진 배열 생성, 2차원

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((3,3),5) # 3*3 배열, 5로 채우기

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.arange(0,10) # 범위를 주면 숫자를 하나씩 증가해서 만들어줌

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- `_like()` : 지정된 배열과 모양이 같은 행렬을 생성

In [ ]:
np.zeros_like(array_a3) # 3차원 (array_a3)로 따라 만들어줌

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

### 지정된 값으로 배열 생성

### 랜덤한 값의 배열 생성

In [ ]:
np.random.random((3,3)) # 3*3 모양으로 랜덤하게 뽑아준다.

array([[0.3728793 , 0.40195195, 0.53762341],
       [0.35183114, 0.74024256, 0.50679481],
       [0.6874009 , 0.94480341, 0.302413  ]])

## 배열의 타입

|Type|Description|
|----|----|
|`bool_`|바이트로 저장된 불리언(Boolean)으로 True 또는 False값을 가짐|
|`int_`|기본 정수(Integer) 타입|
|`int8`|8바이트(Byte) 표현가능한 Integer(-128 to 127)|
|`int16`|16바이트(Byte) 표현가능한 Integer(32768 to 32767)|
|`int32`|32바이트(Byte) 표현가능한 Integer(-2147483648 to 2147483647)|
|`int64`|64바이트(Byte) 표현가능한 Integer(-9223372036854775808 to 9223372036854775807)|
|`uint8`|부호 없는 정수(0 ~ 255)|
|`uint16`|부호 없는 정수(0 ~ 65535)|
|`uint32`|부호 없는 정수(0 ~ 4294967295)|
|`uint64`|부호 없는 정수(0 ~ 18446744073709551615)|
|`float8`|반정밀 부동 소수점(Half precision float): 부호 비트, 5비트 지수, 10비트 가수|
|`float16`|단정밀 부동 소수점(Single precision float): 부호 비트, 8비트 지수, 23비트 가수|
|`float32`|배정밀 부동 소수점(Double precision float): 부호 비트, 11비트 지수, 52비트 가수|
|`float_`|`float64`를 줄여서 표현|
|`complex64`|복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현|
|`complex128`|복소수, 두 개의 64비트 부동 소수점으로 표현|
|`complex_`|`complex128`를 줄여서 표현|

## 배열의 조회

### 배열 속성 정보확인

In [ ]:
array_a3.shape # 3차원(3장), 3*3

(3, 3, 3)

### 인덱싱(Indexing)

In [ ]:
array_a3.size # 배열 안의 요소가 몇개 있나

27

In [ ]:
array_a3.dtype # 배열의 타입

dtype('int64')

### 슬라이싱(Slicing)

In [ ]:
array_a3[0] # 1번째 차원이 나옴

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_a3[0][0] # 1번째 차원의 첫번째 행

array([1, 2, 3])

In [ ]:
array_a3[:2] # 두 번째 차원까지 슬라이싱, [:2] 는 포함 x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
array_a3[:2, :2] # 두 번째 차원까지 슬라이싱, 각 차원마다 두번째 행 까지 슬라이싱

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array_a3[:2, :2, -1] # 두 번째 차원까지 슬라이싱, 각 차원마다 두번째 행 까지 슬라이싱, 마지막 열까지 슬라이싱

array([[3, 6],
       [3, 6]])

In [ ]:
array_a2[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
array_a3[0,:,0] # 차원(1장), 행(전체 선택), 첫번째 열

array([1, 4, 7])

In [ ]:
array_a3[:2, 1: ,1:] # 차원(2장), 행(2,3번째), 열(2,3번째)

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

### 불리언 인덱싱(Boolean Indexing)

In [ ]:
# 마스크를 씌운다.

array_a

array([1, 2, 3])

In [ ]:
array_a[[False,True,False]] # 2를 선택

array([2])

In [ ]:
array_a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
bool_mask = np.array([[True, False,False],
             [False,True,False],
             [False,False,True]])

In [ ]:
array_a2[bool_mask] # True 위치에 있는 값만 불러온다.

array([1, 5, 9])

In [ ]:
np.eye(3,dtype = bool) # 항등행렬, identity matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
array_a2[np.eye(3,dtype = bool)]

array([1, 5, 9])

In [ ]:
np.tri(3, dtype = bool) # 대각 성분 만들기

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [ ]:
array_a2[np.tri(3, dtype = bool)]

array([1, 4, 5, 7, 8, 9])

### 팬시 인덱싱(Fancy Indexing)

In [ ]:
array_a2[[0,1,2],[0,2,0]] # [행 기준, 열 기준]

array([1, 6, 7])

In [ ]:
array_a3[[0,1,2],[0,1,2],[0,1,2]]

array([1, 5, 9])

## 배열의 변환

### 배열 전치

In [ ]:
array_a2.T # 전치

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 배열 재구조화

In [ ]:
np.arange(1,10).reshape(3,3) # 3*3으로 모양 변경

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,28).reshape(3,3,3) # 3*3 으로 3차원으로 변형

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
np.arange(1,10).resize((4,4), refcheck = False) # 나머지 비는 것을

### 배열 크기 변경

In [ ]:
array_a1 = np.arange(1,10)

In [ ]:
array_a1.resize((4,4), refcheck = False) # 나머지 비는 것을 0으로 채워넣음

In [ ]:
array_a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
array_a1 = np.arange(1,10)

In [ ]:
array_a1.resize((2,2), refcheck= False)

In [ ]:
array_a1

array([[1, 2],
       [3, 4]])

### 배열 추가

In [ ]:
array_a1 = np.arange(1,10).reshape(3,3)

In [ ]:
array_a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append(array_a1,array_a1, axis = 1) # 열의 방향으로 붙히기

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
np.append(array_a1, array_a1, axis = 0) # 행의 방향으로 붙히기

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 배열 연결

In [ ]:
np.concatenate([array_a1, array_a1]) # axis = 0 이 default

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack([array_a1,array_a1]) # 수평으로 붙혀달라.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
np.vstack([array_a1,array_a1]) # 수직으로 붙혀달라

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.stack([array_a1,array_a1]) # 차원을 증가시켜 뒤로 붙혀달라.

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### 배열 분할

In [ ]:
array_va1 = np.vstack([array_a1,array_a1])

In [ ]:
np.split(array_va1,[3])

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [ ]:
np.split(array_va1,[1], axis = 1) # 1 앞까지 자름,

[array([[1],
        [4],
        [7],
        [1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9],
        [2, 3],
        [5, 6],
        [8, 9]])]

## 배열 연산  !!중요!!

### 브로드캐스팅(Braodcasting) (자동 채우기)


<figure>
    <img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">
</figure>

In [ ]:
np.arange(3) * 10

array([ 0, 10, 20])

### 산술연산

|Operation|Definition|Descrption|
|--|--|--|
|`+`|`np.add`|덧셈|
|`-`|`np.subtract`|뺄셈|
|`-`|`np.negative`|단향 음수|
|`*`|`np.multiply`|곱셈|
|`/`|`np.divide`|나눗셈|
|`//`|`np.floor_divide`|나눗셈 내림|
|`**`|`np.power`|지수 연산|
|`%`|`np.mod`|나머지 연산|

#### 절대값 (Absolute)

In [ ]:
a = np.random.randint(-100,-50, 10) # (범위, 개수)
np.abs(a)

array([85, 69, 88, 58, 55, 64, 73, 54, 53, 75])

#### 제곱 / 제곱근 (Square / Sqaure root)

In [ ]:
a = np.arange(1,10)
np.square(a) # 제곱

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.sqrt(a) # 제곱근

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

#### 지수 / 로그 (Exponetial / Log)

In [ ]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
np.log(a) # 자연로그

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.log2(a) # 밑이 2인 로그

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

### 비교연산

In [ ]:
np.arange(1,10) >= 5 # 각각의 요소에서 다 물어보고, 결과는 bool로 나옴

array([False, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
np.arange(1,10) >= np.random.randint(1,10,9) # 비교 연산도 broadcasting 적용가능

array([False, False, False, False, False, False,  True,  True,  True])

#### 불리언 연산

In [ ]:
a1 = np.array([0,1,1,0],dtype = bool)
a2 = np.array([0,0,1,0], dtype = bool)

In [ ]:
a1 & a2 # and

array([False, False,  True, False])

In [ ]:
a1 | a2 # shift + 원화

array([False,  True,  True, False])

In [ ]:
~a1# not

array([ True, False, False,  True])